---
title: "ANX_MA_plot"
output: html_document
author: Soumya Kalle
---
```{r, child = "ANX_volcano_plot.Rmd"}
```

Since we focusing on OR values so much, we should check that our data is not biased.
A common plot for meta-analyses is a simple Funnel Plot

#-----------Generating Funnel Plot (Suppl. fig. 2a)------------
```{r}
library(ggplot2)
ANX_full_dataset$logOR <- log(ANX_dataset$OR)

# Build the Funnel Plot
ggplot(ANX_full_dataset, aes(x = logOR, y = SE)) +
  geom_point(alpha = 0.5, color = "mediumpurple") +
  
  scale_y_reverse() + 
  
  # Draw a dashed line to separate protective vs risk odds
  geom_vline(xintercept = 0, linetype = "solid", color = "black") +
  
  # For 95% confidence the standard bounds (at least for metafor library) is +- 1.96 * SE
  # cite: https://wviechtb.github.io/metafor/reference/funnel.html
  geom_abline(intercept = 0, slope = 1/1.96, linetype = "dashed", color = "hotpink") +
  geom_abline(intercept = 0, slope = -1/1.96, linetype = "dashed", color = "hotpink") + 
  theme_minimal() +
  
  labs(title = "Funnel Plot: Bias in OR values",
       x = "log(OR)",
       y = "SE respective to log(OR)") +
theme(
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(family = "serif"),
    axis.title.x = element_text(face = "bold"),
    axis.title.y = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    legend.title = element_text(face = "bold", family = "serif"),
    legend.text = element_text(face = "bold")
  )
```

#-----------Generating Metafor Funnel Plot (Suppl. fig. 2b)------------

```{r}
install.packages("metafor")
library(metafor)
```
```{r}
# Run the Meta-Analysis
anx_rma <- rma(yi = ANX_full_dataset$OR, sei = ANX_full_dataset$SE, data = ANX_full_dataset)


funnel(anx_rma, main = "Metafor Funnel Plot", xlab = "log(OR)")
```


