---
title: "ANX_bar_plot"
output: html_document
---

```{r}
library('readxl')
ANX_data <- read_excel('ANX_2026_daner_fullANX_v12_woUTAH_11022026.gz.p4.clump.areator.sorted.1mhc (1).xls')
```
```{r}
library('tidyverse')

chr_distances_1 <- list()

for(chr_num in 1:10){
  chr_data <- ANX_data %>% 
    filter(CHR == chr_num) %>% 
    arrange(BP)
  # 2. Only calculate distances if there are at least 2 SNPs
  #    because you need a current SNP and a next SNP to find a distance
  if (nrow(chr_data) >= 2) {
    
    # 3. Create a table comparing each SNP to the next SNP
    distance_table <- data.frame(
      CHR = chr_num,                         # chromosome number
      SNP = chr_data$SNP[-nrow(chr_data)],   # all SNPs except the last one
      PVal = chr_data$P[-nrow(chr_data)],    # corresponding PVals
      curr_SNP_pos = chr_data$BP[-nrow(chr_data)], # all positions except the last one
      next_SNP_pos = chr_data$BP[-1],            # all positions except the first one
      BP_diff = diff(chr_data$BP)           # distance between neighboring SNPs
    )
    
    # 4. Store this chromosome's distance table in the list
    chr_distances_1[[chr_num]] <- distance_table
  }
}

# 5. Combine all chromosome tables into one big data frame
chr_distances_1  <- do.call(rbind, chr_distances_1)

# 3. Classify each distance into your table's custom scales!
chr_distances_1  <- chr_distances_1  %>% 
  mutate(
    Classification = case_when(
      BP_diff < 20000                  ~ "very close",
      BP_diff >= 20000 & BP_diff < 100000   ~ "close",
      BP_diff >= 100000 & BP_diff < 1000000 ~ "far",
      BP_diff >= 1000000               ~ "very far"
    )
  )


# View the final table
chr_distances_1 
```


Above is distance table 1 (Chromosomes 1-10)
Below is distance table 2 (Chromosomes 11-22)


```{r}
#new empty list thats going to hold all chromosome distances, each entry is a dataframe
chr_distances_2 <- list()

for(chr_num in 11:22){
  chr_data <- ANX_data %>% 
    filter(CHR == chr_num) %>% 
    arrange(BP)
  # 2. Only calculate distances if there are at least 2 SNPs
  #    because you need a current SNP and a next SNP to find a distance
  if (nrow(chr_data) >= 2) {
    
    # 3. Create a table comparing each SNP to the next SNP
    distance_table <- data.frame(
      CHR = chr_num,                         # chromosome number
      SNP = chr_data$SNP[-nrow(chr_data)],   # all SNPs except the last one
      PVal = chr_data$P[-nrow(chr_data)],    # corresponding PVals
      curr_SNP_pos = chr_data$BP[-nrow(chr_data)], # all positions except the last one
      next_SNP_pos = chr_data$BP[-1],            # all positions except the first one
      BP_diff = diff(chr_data$BP)           # distance between neighboring SNPs
    )
    
    # 4. Store this chromosome's distance table in the list
    chr_distances_2[[chr_num]] <- distance_table
  }
}

# 5. Combine all chromosome tables into one big data frame
chr_distances_2 <- do.call(rbind, chr_distances_2)

# 3. Classify each distance into your table's custom scales!
chr_distances_2 <- chr_distances_2 %>% 
  mutate(
    Classification = case_when(
      BP_diff < 20000                  ~ "very close",
      BP_diff >= 20000 & BP_diff < 100000   ~ "close",
      BP_diff >= 100000 & BP_diff < 1000000 ~ "far",
      BP_diff >= 1000000               ~ "very far"
    )
  )


# View the final table
chr_distances_2 


```




CREATING A LIST/DICTIONARY FOR VERY CLOSE PAIRS BELOW
```{r}

closepairs <- list()
close_SNPs <- c()
volcano_SNP_overlaps <- c()

#loops through chr_distances_1 and 2, pulls out rows (SNPS) classified as very close, and adds that SNP
#and the next (very close to each other) as well as the chromosome number to a list (dictionary)

#also adds the SNP to list volcano_SNP_overlaps to analyze/compare data with volcano plot

for (i in 1:length(chr_distances_1$Classification)) {
  if (chr_distances_1$Classification[i] == 'very close') {
    closepairs <- append(closepairs, list(c(chr_distances_1$CHR[i], chr_distances_1$SNP[i], chr_distances_1$PVal[i], chr_distances_1$SNP[i+1], chr_distances_1$PVal[i+1])))
    close_SNPs <- append(volcano_SNP_overlaps, chr_distances_1$SNP[i])
  }
}


for (i in 1:length(chr_distances_2$Classification)) {
  if (chr_distances_2$Classification[i] == 'very close') {
    closepairs <- append(closepairs, list(c(chr_distances_2$CHR[i], chr_distances_2$SNP[i], chr_distances_2$PVal[i], chr_distances_2$SNP[i+1], chr_distances_2$PVal[i+1]))) 
    close_SNPs <- append(volcano_SNP_overlaps, chr_distances_2$SNP[i])
  }
}

closepairs
```


Examine the SNPS and PVals
```{r}
ANX_data <- rename(ANX_data,'genelist' = 'genes.6.50kb(dist2index)')
SNP_names <- c()
SNP_pval <- c()
for (i in 1:length(chr_distances_1$Classification)) {
  if (chr_distances_1$Classification[i] == 'very close') {
    SNP_names <- c(SNP_names, chr_distances_1$SNP[i], chr_distances_1$SNP[i+1])
    SNP_pval <- c(SNP_pval, chr_distances_1$PVal[i], chr_distances_1$PVal[i+1])
  }
}

for (i in 1:length(chr_distances_2$Classification)) {
  if (chr_distances_2$Classification[i] == 'very close') {
    SNP_names <- c(SNP_names, chr_distances_2$SNP[i], chr_distances_2$SNP[i+1])
    SNP_pval <- c(SNP_pval, chr_distances_2$PVal[i], chr_distances_2$PVal[i+1])
  }
}
SNP_names
SNP_pval
```
Graph Plot 3 so far by factoring pairs
```{r}
column_list <- list(
  Name = SNP_names,
  PVal = -log10(SNP_pval)
)
df_data <- as.data.frame(column_list)
pair_num <- 1
df_data$col <- 1
df_data$genes <- NA
for (i in 1:nrow(df_data)){
  if (i > 2){
    if (df_data$col[i-1] == df_data$col[i-2]){
        pair_num <- pair_num + 1
    }
  }
  df_data$col[i] <- pair_num
  df_data$genes[i] <- ANX_data$genelist[ANX_data$SNP == df_data$Name[i]]
}
df_data

palette_cols <- hcl.colors(30, palette = "Dynamic")
ggplot(df_data, aes(x = factor(Name, levels = unique(Name)), y = PVal, fill = factor(col))) + geom_col() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + scale_fill_manual(values = palette_cols)

```

The genes list for each pair
```{r}
library(stringr)
library(tidyr)
pairdf <- as.data.frame(do.call(rbind, closepairs))
colnames(pairdf) <- c('Chromosome', 'SNP1', 'Pval1', 'SNP2', 'Pval2')

genevec <- c()
for (i in seq(from = 1, to = 48, by = 2)) { #Only every two because each 2 rows is one pair
    if (grepl("0.0", df_data$genes[i], fixed = TRUE)) {
      genevec <- append(genevec, df_data$genes[i])
    } 
    else{
      genevec <- append(genevec, 'NA')
    }
}
genevec
```

```{r}
gene_legend <- genevec
gene_legend2 <- c()

tempvec <- c()
num <- 1 # for annotation purposes

for (i in 1:length(gene_legend)) { # for all the 24 elements in this list
  
  # if an element has a comma, the element has multiple genes
  if (grepl(",", gene_legend[i])) { 
    
    tempvec <- trimws(unlist(strsplit(gene_legend[i], ','))) # vectorize these genes
    zero_genes <- grep("0.0", tempvec, value = TRUE)
    
    # for each gene in the vectorized list && if we haven't already found  0.0 gene
    if (length(zero_genes) == 1) {
        gene_legend[i] <- zero_genes[1]
    } else {
        gene_legend[i] <- paste0("[", num, "]")
        genevec[i] <- paste0("[", num, "] ",  genevec[i])
        gene_legend2 <- append(genevec[i], gene_legend2)
        num <- num + 1

    }
  }
}
gene_legend

```
```{r}
gene_legend2 # the full genes list
```


```{r}
genevec
```

```{r}
# 1. Update the ggplot code with the labels argument
ggplot(df_data, aes(x = factor(Name, levels = unique(Name)), y = PVal, fill = factor(col))) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
  scale_fill_manual(
    values = palette_cols,
    labels = gene_legend, # Each pair is assigned its Gene
    name = "Genes"        
  ) 
  

```

```{r}
# Create column col to set up values 1 to 24
df_data$col <- rep(1:24, each = 2)[1:nrow(df_data)]

# Previous graphs we made were too complex => split in half
df_part1 <- subset(df_data, col <= 12)
df_part2 <- subset(df_data, col > 12)

# Split the color palette too
palette_part1 <- palette_cols[1:12]
palette_part2 <- palette_cols[13:24]

# Split the legend too
legend_part1 <- gene_legend[1:12]
legend_part2 <- gene_legend[13:24]
```

#-----------Generating Bar Plot (Suppl. fig. 3a)------------
```{r}
# Extract every second name to use as breaks (creates a tick mark every 2 SNPs / at every pair)
breaks_part1 <- unique(df_part1$Name)[seq(1, length(unique(df_part1$Name)), by = 2)]

# Create a clean label for those ticks, like "Pair 1", "Pair 2", etc.
labels_part1 <- paste("Pair", 1:12)

ggplot(df_part1, aes(x = factor(Name, levels = unique(Name)), y = PVal, fill = factor(col))) +  
  geom_col() +  
  scale_x_discrete(
    breaks = breaks_part1,  # Forces a tick mark every 2 SNPs
    labels = labels_part1   # Names them cleanly 
  ) +
  theme(
    axis.text.x = element_text(vjust = 0.5, hjust = 0.5), # text alignment
    axis.ticks.x = element_line(),                        # Ensures the tick marks show up
    plot.title = element_text(face = "bold"),
    axis.title.x = element_text(face = "bold"),
    axis.title.y = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  ) +  
  scale_fill_manual(
    values = palette_part1,
    labels = legend_part1,
    name = "Genes (1-12)"
  ) +
  labs(x = "SNP Pairs",
       title = "Pairwise Analysis of SNP Pairs (1-12)",
       subtitle = "Very Close Classification (< 20kbp)")
```
#-----------Generating Bar Plot (Suppl. fig. 3b)------------

```{r}
# Extract every second name for the second half
breaks_part2 <- unique(df_part2$Name)[seq(1, length(unique(df_part2$Name)), by = 2)]
labels_part2 <- paste("Pair", 13:24)

ggplot(df_part2, aes(x = factor(Name, levels = unique(Name)), y = PVal, fill = factor(col))) +  
  geom_col() +  
  scale_x_discrete(
    breaks = breaks_part2,  
    labels = labels_part2   
  ) +
  theme(
    axis.text.x = element_text(vjust = 0.5, hjust = 0.5), 
    axis.ticks.x = element_line(), 
    plot.title = element_text(face = "bold"),
    axis.title.x = element_text(face = "bold"),
    axis.title.y = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  ) +  
  scale_fill_manual(
    values = palette_part2,
    labels = legend_part2,
    name = "Genes (13-24)"
  ) +
  labs(x = "SNP Pairs",
       title = "Pairwise Analysis of SNP Pairs (13-24)",
       subtitle = "Very Close Classification (< 20kbp)")
```


No overlaps from the significant pairs from the volcano plot
```{r}
 
sig_from_volcano <- c("rs58825580", "rs7110863",  "rs10959883", "rs11241568", "rs4976976",  "rs10476497", "rs77960")
overlaps <- c()
for (i in 1:length(close_SNPs)) {
  for (j in 1:length(sig_from_volcano)) {
    if (sig_from_volcano[j] == close_SNPs[i]) {
    overlaps <- append(overlaps, close_SNPs[i])
    }
  }
}
overlaps
```
